// Page copy for /approve/[tipId] (AGENTS.md rule 14). Outcome and World texts live in lib/messages.ts.
export const APPROVE_COPY = {
  TITLE: "Approve a held tip",
  LOADING: "Loading…",
  NOT_FOUND: "No held tip with this id.",
  LOAD_FAILED: "Could not load this tip ({error}).",
  PACKAGE: "Package",
  AMOUNT: "Amount",
  PAYEE: "Payee",
  NO_PAYEE: "no payee on record",
  REASON: "Why it was held",
  STATUS: "Status",
  EXPIRES_IN: "Expires in {time}",
  APPROVE_WORLD: "Approve with World ID",
  APPROVE: "Approve",
  DENY: "Deny",
  WORKING: "Working…",
  REDIRECTING: "Opening World ID…",
  SIGN_IN: "Sign in as the owner to approve or deny.",
  SIGN_IN_LINK: "Go to sign in",
  NOT_OWNER: "This tip belongs to a different owner.",
  RELEASE_TX: "Release transaction",
  REFUND_TX: "Refund transaction",
  STATUS_PENDING: "Waiting for the owner",
  STATUS_APPROVED: "Approved",
  STATUS_DENIED: "Denied",
  STATUS_EXPIRED: "Expired",
  EXPIRED_REFUND_PENDING: "Not approved in time. The refund to the owner is on its way.",
  LAST_ATTEMPT: "Last attempt failed:",
  // Action errors from POST /start and /deny.
  ERR_UNAUTHORIZED: "Your owner session has ended. Sign in again.",
  ERR_WORLD_REQUIRED: "Approval needs World ID on this deployment.",
  ERR_NOT_FOUND: "This tip is not one of yours.",
  ERR_NOT_PENDING: "This tip was already resolved.",
  ERR_WORLD_NOT_BOUND: "Sign in with World ID on the owner page first, then approve.",
  ERR_RELEASE_CHAIN: "The release transaction failed ({code}). Nothing was released.",
  ERR_REFUND_CHAIN: "The refund transaction failed ({code}). Nothing was refunded.",
  ERR_OTHER: "Something went wrong ({error}). Nothing was released.",
} as const;
