// Copy for the budget wallet component (components/budget/*, EndCreditsBudget; AGENTS.md rule 14).
export const BUDGET_COPY = {
  TITLE: "Budget wallet",
  EXPLAIN:
    "Your USDC stays in your own wallet. You approve USDC to the budget contract and let our agent key pull at most a set amount per period. Each session pulls exactly what it spends, once, before anything is paid. Lower or revoke it any time.",
  NOT_CONFIGURED: "Spend limits are not switched on for this server yet.",
  WALLET: "Budget wallet",
  NONE: "none",
  SPENDER: "Agent key",
  BALANCE: "USDC in the wallet",
  APPROVED: "USDC approved to the budget contract",
  ALLOWANCE: "Allowance",
  ALLOWANCE_LINE: "{perPeriod} USDC per {period}, {spent} spent this period, {remaining} left",
  NO_ALLOWANCE: "No allowance yet. Nothing can be pulled.",
  RPC: "Could not read the chain right now.",
  CONNECT: "Connect wallet",
  CONNECT_BROWSER: "Use browser wallet",
  CONNECTING: "Opening wallet…",
  CONNECTED: "Connected",
  USE_WALLET: "Use this wallet as the budget wallet",
  WRONG_WALLET: "Connect the budget wallet {budgetOwner} to change its allowance; this is {address}.",
  PER_PERIOD: "Per period (USDC)",
  PERIOD: "Period",
  PERIODS: { "3600": "hour", "86400": "day", "604800": "week" } as Record<string, string>,
  APPROVE_AMOUNT: "Approve (USDC)",
  APPROVE: "Approve USDC",
  SET_ALLOWANCE: "Set allowance",
  REVOKE: "Revoke",
  CONFIRM: "Confirm in your wallet…",
  SENT: "Sent. It shows here once the block lands.",
  SAVED: "Budget wallet saved.",
  BAD_AMOUNT: "Enter an amount like 20 or 2.5.",
  FAILED: "Did not go through ({error}).",
  LOAD_FAILED: "Could not read the budget wallet ({error}).",
} as const;
