export const CONTROL = {
  eyebrow: "OWNER WORKSPACE",
  title: "Your control room.",
  subtitle:
    "Set the budget. Connect your agent. Stay in charge of every release.",
  tabs: [
    { id: "budget", title: "Budget & wallet", hint: "How much, and when" },
    {
      id: "keys",
      title: "Agent connection",
      hint: "Connect your next session",
    },
    { id: "approvals", title: "Approvals", hint: "Review, sign, and release" },
  ],
  budgetTitle: "Make room for a thank-you.",
  budgetBody:
    "These limits apply to your agent’s contributions. Changes take effect after you save.",
  sessionHint: "Maximum allocated per session",
  capHint: "Maximum for a single package",
  dailyHint: "Your daily contribution ceiling",
  timing: "When should contributions run?",
  modeHint:
    "Choose whether to settle automatically or when you open the credits roll.",
  holdHint: "Unapproved holds are eligible for refund after this time.",
  savedPolicy: "SAVED POLICY",
  savedBody: "The settings currently recorded by the server.",
  savedTitle: "Contribution settings saved",
  savedDetail: "Your saved policy now matches these limits.",
  unsaved: "Unsaved changes",
  upToDate: "All changes saved",
  discard: "Reset changes",
  unit: "USDC",
  minutes: "minutes",
  capPreview: "PACKAGE CAP / SESSION BUDGET",
  capPreviewNote: "A maximum per package, not a promised payment.",
  walletLabel: "FUNDING WALLET",
  walletNote: "USDC available to the configured payer on Base Sepolia.",
  walletUnavailable: "Balance unavailable",
  viewWallet: "View wallet ↗",
  copyAddress: "Copy address",
  copied: "Address copied",
  copyFailed: "Could not copy. Select the address to copy it manually.",
  walletFoot:
    "Your funding wallet sends contributions. The approver wallet separately authorizes held releases.",
  reviewTitle: "A clear path to a decision.",
  reviewBody:
    "Read the reason, verify the recipient, then sign or deny. A wallet signature does not itself confirm a transfer.",
  reviewSteps: [
    "Review the details",
    "Sign with your wallet",
    "Verify the outcome",
  ],
  reviewLabel: "RELEASE WORKFLOW",
  keyTitle: "Give your agent a connection.",
  keyBody:
    "Create a key for each device. Install the CLI, add the key locally, and initialize hooks in your project.",
  keySteps: ["Create an agent key", "Connect the CLI", "Run your next session"],
  connectedTitle: "Wallet connected",
  connectedBody: "Connection confirmed. No transaction was sent.",
  approverTitle: "Approver updated",
  approverPending: "Approver change scheduled",
  approverSaved: "The server has recorded this wallet.",
  approverWait:
    "The current on-chain approver stays active until the displayed activation time.",
  prepare: "Prepare release",
  wallet: "Open wallet",
  sign: "Sign approval",
  submit: "Verify signature",
  execute: "Release funds",
  signHint:
    "Confirm the request in your wallet. End Credits checks the signature before requesting a release.",
  submitHint: "The server is verifying and recording your signature.",
  executeHint: "Waiting for the server’s release result. Keep this page open.",
  retry: "Try again",
  dismiss: "Dismiss notification",
  success: "Completed",
  working: "In progress",
  keyCreated: "Agent key created",
  keyRevoked: "Agent key revoked",
  keyRevokeBody: "This key can no longer authenticate new requests.",
  keyCopyFailed: "Copy failed. Select the key or command and copy it manually.",
  approvalTitle: "Review this contribution.",
  approvalEyebrow: "HELD IN ESCROW",
  approvalSummary:
    "Verify the amount, payee, and reason before releasing funds.",
  backControls: "Back to approvals",
  denying: "Requesting refund",
  denyingBody: "Waiting for the server to record the denial and refund result.",
} as const;
export const INSIGHTS = {
  actions: "Needs your attention",
  actionsBody: "Next steps from escrow activity and recorded package details.",
  noActions: "You’re all caught up.",
  noActionsBody: "There are no pending actions in this activity snapshot.",
  source: "Source",
  review: "Review →",
  actionKind: {
    hold_expiring: "Expiring soon",
    approve_hold: "Approval needed",
    reserve_waiting: "Waiting for maintainer",
  },
  timeline: "Where the credits went.",
  timelineLabel: "48-HOUR ACTIVITY",
  timelineBody:
    "Hourly USDC movements, indexed by MultiBaas. All times are UTC.",
  series: {
    paid: "Paid",
    held: "Held",
    released: "Released",
    refunded: "Refunded",
    reserved: "Reserved",
    claimed: "Claimed",
  },
  noEvents: "No recorded movement in this window.",
  chartLabel:
    "Hourly USDC activity. Choose a series and focus a bar to inspect an hour.",
  table: "View hourly data",
  hour: "Hour (UTC)",
  amount: "USDC",
  currentHour: "Current hour",
  missingTimeline: "Hourly activity is not available in this response.",
  payerScreen: "Payer wallet",
  simulationScreen: "Payment simulation",
  payerNoHistory: "No mainnet history. The payer screen accepts this result.",
  screenMapping: "Screening context",
  risk: "Counterparty profile",
  riskLabel: "STORED SCREENING EVIDENCE",
  riskBody:
    "Evidence for the payout address, from our database. This is not a new scan or a guarantee of safety.",
  riskError:
    "The counterparty profile could not be loaded. Other package details are still available.",
  noPayee:
    "No payout wallet is listed yet. A counterparty profile becomes available when there is a payee.",
  noRisk: "No counterparty profile is available yet.",
  noScreens: "No successful address screening is recorded.",
  noHistory:
    "Intercepta has no history for this address. This is not a clean verdict.",
  score: "Toxic score",
  screened: "Address screened",
  screens: "Stored screens",
  decisions: "Recorded decisions",
  sessions: "Sessions",
  traits: "Reported traits",
  noTraits: "No traits were reported by this stored scan.",
  impersonation: "Impersonation check",
  noImpersonation: "No impersonation result recorded.",
  poisoned: "Address poisoning reported",
  notPoisoned: "No address poisoning reported in this scan",
  original: "Original address",
  simulation: "Simulation detectors",
  noSimulation: "No simulation result recorded.",
  noDetectors: "No detectors were reported by this stored simulation.",
  observations: "Funding address history",
  changed: "Address changed",
  current: "Current",
  previous: "Previous",
  firstSeen: "First observed",
  lastSeen: "Last observed",
  noObservations: "No funding address observations recorded.",
  outcomes: "Decision history for this address",
  outcomeNote: "Allocation totals by decision. These are not payment totals.",
  latest: "Latest decision",
  rawProfile: "View stored profile JSON ↗",
  reasonTitle: "Decision evidence",
  reasonKind: {
    payment: "Payment simulation",
    payer: "Payer screening",
    other: "Decision reason",
  },
  showAll: "All recorded reasons",
  unit: "USDC",
} as const;
