export const CREDITS_DESK = {
  eyebrow: "SESSION CREDITS",
  title: "Every build has a cast.",
  intro:
    "The open-source work behind this session, with a decision and a receipt for every credit.",
  ticket: "SESSION / CONTRIBUTION RECORD",
  cast: "The supporting cast",
  castNote: "Grouped by how each package contributed to your session.",
  packages: "Packages credited",
  session: "Session ID",
  started: "Started",
  ended: "Ended",
  record: "View session record ↗",
  network: "Base Sepolia · testnet USDC",
  details: "Decision & evidence",
  package: "Package profile ↗",
  approval: "Review hold ↗",
  claim: "View reserved credits ↗",
  transaction: "Transaction ↗",
  noTransaction: "No transaction recorded",
  payee: "Payee",
  pending: "Awaiting a decision",
  noEvidence: "No decision evidence has been returned yet.",
  all: "All credits",
  filters: "Filter credits by outcome",
  noResults: "No credits match this filter.",
  reset: "Show all credits",
  allocations: "Decision allocations",
  allocationsNote:
    "These amounts describe decisions. A transaction link is the evidence of execution.",
  allocated: "Allocated to pay",
  held: "Held",
  reserved: "Reserved",
  refused: "Refused packages",
  outcomes: {
    paid: "Paid",
    capped: "Capped",
    held: "Held",
    reserved: "Reserved",
    refused: "Refused",
    dust: "Dust",
  },
  progress: "Decisions recorded",
  retry: "Refresh session",
  emptyTitle: "No cast to credit yet.",
  loadingTitle: "Finding this session’s cast…",
  state: {
    uploaded: "Ready to roll",
    settling: "Credits in progress",
    settled: "Processing complete",
    failed: "Processing failed",
  },
  usdc: "USDC",
  explanation:
    "Observed in your AI session. Screened before signing. Recorded for you to inspect.",
} as const;
