// T8.4 / T8.1–T8.3: product and marketing presentation copy.
export const EXPERIENCE = {
  name: "End Credits",
  nav: "Main navigation",
  skip: "Skip to content",
  menu: "Open navigation",
  close: "Close navigation",
  app: "Open app",
  how: "How it works",
  why: "Why give back",
  source: "Source code",
  github: "https://github.com/zexoverz/end-credits",
  eyebrow: "FOR THE OPEN SOURCE BEHIND YOUR AI",
  hero: ["Your agent ships.", "Who gets", "the credit?"],
  intro:
    "Turn a Claude Code session into support for the open-source packages it used. Your budget. Their credit.",
  cta: "Set up End Credits",
  secondary: "See how it works",
  footnote: "Voluntary contributions · Testnet USDC on Base Sepolia",
  example: "ILLUSTRATIVE SESSION",
  agent: "Claude Code",
  prompt: "Build a better checkout.",
  agentDone: "Built with a little help from open source.",
  receipt: "The credits go to…",
  receiptNote: "Usage recorded. Contributions recognized.",
  packages: [
    {
      name: "zod",
      role: "Validation",
      mark: "z",
      url: "https://github.com/colinhacks/zod",
    },
    {
      name: "date-fns",
      role: "Date handling",
      mark: "d",
      url: "https://github.com/date-fns/date-fns",
    },
    {
      name: "chalk",
      role: "Terminal colors",
      mark: "c",
      url: "https://github.com/chalk/chalk",
    },
    {
      name: "Prettier",
      role: "Code formatting",
      mark: "p",
      url: "https://github.com/prettier/prettier",
    },
    {
      name: "Vitest",
      role: "Testing",
      mark: "v",
      url: "https://github.com/vitest-dev/vitest",
    },
    {
      name: "pnpm",
      role: "Package management",
      mark: "pn",
      url: "https://github.com/pnpm/pnpm",
    },
  ],
  packageHeading: "A whole cast behind every build.",
  packageBody:
    "Validators. Test runners. The tiny utility that just works. Your agent uses their work. End Credits helps you recognize it.",
  packageNote:
    "Examples of open-source projects in the ecosystem, not customers or endorsements.",
  problemLabel: "THE MISSING THANK-YOU",
  problemTitle: ["AI moves fast.", "Support should follow."],
  problemBody:
    "Developers pay for the agent. The packages underneath it are still maintained by people. End Credits connects the work your agent uses to a contribution you choose.",
  value: "$8.8T",
  valueTitle: "of open-source value to firms",
  valueBody:
    "Estimated cost to recreate the open-source software firms use. Replacement value, not market revenue.",
  valueSource: "Harvard Business School research · 2024 ↗",
  valueUrl:
    "https://www.library.hbs.edu/working-knowledge/open-source-software-the-nine-trillion-resource-companies-take-for-granted",
  gap: "2.1%",
  gapTitle: "listed a payable wallet",
  gapBody:
    "In our top-1,000 npm package snapshot, 416 had funding metadata. Just 21 listed a wallet across the sources we checked.",
  gapSource: "Our registry snapshot · 25 Sep 2026 ↗",
  gapUrl: "https://github.com/zexoverz/end-credits/blob/main/docs/plan/SPEC.md",
  gapNote:
    "929 registry reads; 71 rate-limited. Percentages use the full 1,000-package sample.",
  flowLabel: "ONE SESSION. EVERY CONTRIBUTION.",
  flowTitle: ["Keep building.", "Leave something behind."],
  flowIntro:
    "Connect once, set your limits, and let the end of a session become the start of giving back.",
  flowTabs: "Explore the session workflow",
  steps: [
    {
      label: "01",
      title: "Your agent does its thing.",
      body: "The Claude Code hook records package reads, imports, and installs locally. Your code and repository paths stay on your machine.",
      screen: "PACKAGE ACTIVITY",
      lines: [
        "import { z } from 'zod'",
        "import { format } from 'date-fns'",
        "import chalk from 'chalk'",
      ],
      footer: "Package signals, not your source code.",
    },
    {
      label: "02",
      title: "Give every package its part.",
      body: "End Credits attributes contributions and splits your session budget by usage. A per-package cap keeps the allocation within your limits.",
      screen: "YOUR CONTRIBUTION",
      lines: [
        "Session budget → your choice",
        "Package shares → weighted by usage",
        "Per-package cap → always applied",
      ],
      footer: "Opt in. Set a budget. Stay in control.",
    },
    {
      label: "03",
      title: "Screen first. Then roll credits.",
      body: "Every payee is screened before signing. Cleared payees can receive USDC; uncertain payments wait, and packages without wallets can claim reserved funds.",
      screen: "END CREDITS",
      lines: [
        "Payee → checked with Intercepta",
        "Decision → recorded before signing",
        "Receipt → inspect the transaction",
      ],
      footer: "Every decision leaves a reason.",
    },
  ],
  controlsLabel: "GENEROSITY, WITH BOUNDARIES",
  controlsTitle: "A little trust.\nA lot of checks.",
  controls: [
    {
      title: "You set the budget.",
      body: "Choose what a session can spend, a daily limit, and a maximum share per package. No surprise open tabs.",
      icon: "budget",
    },
    {
      title: "Uncertainty means pause.",
      body: "A screening error means hold, never pay. Escrowed holds need approval; denial or expiry makes them refundable.",
      icon: "shield",
    },
    {
      title: "No wallet? Still counted.",
      body: "A package’s share can wait in escrow. Maintainers prove GitHub ownership and publish a wallet to claim it.",
      icon: "package",
    },
  ],
  maintainer: "Maintain something people build on?",
  maintainerBody:
    "Find your package, inspect its reserved credits, and connect a payout wallet.",
  maintainerAction: "Find your package",
  searchLabel: "npm package name",
  searchPlaceholder: "e.g. zod or @scope/package",
  searchInvalid: "Enter a valid npm package name.",
  setupLabel: "READY FOR YOUR NEXT SESSION",
  setupTitle: ["Ship something good.", "Give something back."],
  setupBody:
    "Build the CLI from source, create an agent key, and install the hook in your project.",
  setupAction: "Create an agent key",
  terminalTitle: "In your local clone",
  commands: [
    "pnpm install",
    "pnpm --filter endcredits build",
    "cd cli && npm link && cd ..",
    "endcredits init",
    "endcredits key <token> --api https://end-credits.up.railway.app",
  ],
  setupHint:
    "Clone the source first. Run init inside your project and replace <token> with your agent key.",
  copy: "Copy commands",
  copied: "Copied",
  copyError: "Copy failed. Select the commands and copy them manually.",
  footer: "For the people behind the packages.",
  footerNote: "ETHGlobal Tokyo 2026 · Open source",
  shellLabel: "WORKSPACE",
  shellNav: [
    ["/app", "Overview"],
    ["/app/history", "Decisions"],
    ["/app/packages", "Find a package"],
    ["/app/owner", "Settings & keys"],
  ],
  shellNetwork: "Base Sepolia",
  shellTestnet: "Testnet workspace",
  shellHelp: "Connect your agent",
  shellHelpBody: "A small setup for every session that follows.",
  shellHelpAction: "Get started ↗",
  shellBack: "About End Credits ↗",
  pageEyebrow: "END CREDITS / WORKSPACE",
  screening: "Screening…",
  overviewIntro: "Follow the open source your agent supports.",
  setupBanner: "Give your next session end credits.",
  setupBannerBody:
    "Set a budget and connect an agent key to start recording package contributions.",
  setupBannerAction: "Connect agent ↗",
  decisionSearch: "Search packages or reasons",
  all: "All outcomes",
  outcomes: ["paid", "capped", "held", "reserved", "refused", "dust"],
  noMatches: "No decisions match these filters.",
  resultCount: "{count} decisions shown",
  decisionDetails: "Reasons & screening",
  allocationNote:
    "Amounts are allocations. A transaction link confirms execution.",
  paidTransfers: "Confirmed transfers",
  noTransfer: "No transaction recorded",
  allocationSummary:
    "Payment allocation: {paid} USDC. Hold allocation: {held} USDC. Reserve allocation: {reserved} USDC. Refused: {refused}.",
  completed: "Processing complete. Check each credit for its transaction.",
  transferScope:
    "Confirmed payer transfers exclude escrow deposits and may include transfers outside credited sessions.",
  decisionTotals: "Allocation summary",
  confirmed: "Confirmed payment total",
  reason: "Decision details",
  session: "SESSION CREDITS",
  packagePage: "Find a package",
  packageIntro:
    "Look up an npm package to see its credits and maintainer claim options.",
  packageSearch: "Look up package",
  retry: "Try again",
} as const;
