// Page copy for /owner (AGENTS.md rule 14). World failure texts live in lib/messages.ts.
export const OWNER_COPY = {
  TITLE: "Owner",
  LOADING: "Loading…",
  LOAD_FAILED: "Could not load the owner page ({error}).",
  SIGNED_OUT: "Sign in to manage budgets, agent keys and held tips.",
  WORLD_SIGN_IN: "Sign in with World ID",
  DEV_TOKEN: "Owner dev token",
  DEV_SIGN_IN: "Sign in with dev token",
  DEV_BAD_TOKEN: "That token is not the owner dev token.",
  DEV_WORLD_REQUIRED: "Dev sign-in is off here. Sign in with World ID.",
  DEV_NO_OWNER: "No owner exists yet. Run the seed first.",
  DEV_FAILED: "Sign-in failed ({error}).",
  WORLD_STATE: "The sign-in did not match this browser. Try again.",
  WORLD_NO_OWNER: "No owner exists yet to bind this World ID to.",
  SIGNED_IN_AS: "Signed in as {name}",
  LOGOUT: "Sign out",
  PAYER: "Payer",
  BALANCE_ERROR: "Balance unavailable ({error}).",
  SETTINGS: "Settings",
  BUDGET: "Session budget (USDC)",
  CAP: "Per-package cap (USDC)",
  DAILY: "Daily limit (USDC)",
  TTL: "Hold time (minutes)",
  TTL_HINT: "1 minute to 7 days (10080 minutes).",
  SETTLE_MODE: "Settle mode",
  SETTLE_ON_OPEN: "When I open the roll",
  SETTLE_AUTO: "Automatically",
  SAVE: "Save settings",
  SAVING: "Saving…",
  SAVED: "Saved.",
  ERR_USDC: "Enter a USDC amount like 0.25.",
  ERR_TTL: "Enter whole minutes from 1 to 10080.",
  ERR_CAP_OVER_BUDGET: "The per-package cap may not exceed the session budget.",
  ERR_SAVE: "Could not save ({error}).",
  KEYS: "Agent keys",
  KEY_LABEL: "Label",
  KEY_LABEL_PLACEHOLDER: "laptop",
  KEY_CREATE: "Create key",
  KEY_CREATED: "Copy this key now. It is not shown again.",
  KEY_COMMAND: "Run on the agent's machine:",
  COPY: "Copy",
  COPIED: "Copied",
  KEY_DONE: "Done",
  KEY_REVOKE: "Revoke",
  KEY_REVOKED: "revoked {time}",
  KEY_ACTIVE: "active, created {time}",
  KEY_NONE: "No agent keys yet.",
  KEY_ERR: "Could not update keys ({error}).",
  KEY_LABEL_REQUIRED: "Give the key a label.",
  HOLDS: "Held tips",
  HOLDS_NONE: "Nothing is waiting for you.",
  HOLD_OPEN: "Review",
  HOLD_EXPIRES: "expires in {time}",
  HOLD_EXPIRED: "expired, refund pending",
  NO_PAYEE: "no payee",
  NOTIFICATIONS: "Notifications",
  UNREAD: "{count} unread",
  NOTIFICATIONS_NONE: "No unread notifications.",
} as const;
