export const STUDIO = {
  title: "Your open-source studio.",
  subtitle: "A home for the packages behind your AI sessions.",
  workspace: "Personal workspace",
  workspaceNote: "Base Sepolia · testnet",
  nav: [
    ["/app", "Overview"],
    ["/app/sessions", "Sessions"],
    ["/app/packages", "Packages"],
    ["/app/history", "Decisions"],
    ["/app/owner", "Settings"],
  ],
  navigation: "Workspace navigation",
  about: "About End Credits",
  help: "Setup guide",
  helpTitle: "Give your agent a way to give back.",
  helpBody: "Three small steps. Then back to building.",
  close: "Close setup guide",
  setupSteps: [
    {
      title: "Choose your limits",
      body: "Sign in, choose a session budget, and set a per-package cap.",
      action: "Open budget settings",
      href: "/app/owner",
    },
    {
      title: "Connect Claude Code",
      body: "Create an agent key, build the CLI, and install the hook inside your project.",
      action: "Create an agent key",
      href: "/app/owner?section=keys",
    },
    {
      title: "Build. Then roll credits.",
      body: "Run a session as usual. Open the session link from your CLI to inspect its package credits.",
      action: "View installation commands",
      href: "/landing#setup",
    },
  ],
  greeting: "EVERY BUILD HAS A CAST",
  welcome: "Great work starts\nwith a little help.",
  activeTitle: "Good work leaves a trail.",
  activeBody:
    "Open a session to follow its packages, inspect the decisions, and find the receipts.",
  activeAction: "Explore your sessions",
  welcomeBody:
    "Connect Claude Code and give the packages behind your next session their end credits.",
  connect: "Connect your agent",
  openSession: "Open a session",
  sessionLabel: "Session ID or End Credits session link",
  sessionPlaceholder: "Paste your session ID or credits link",
  sessionInvalid:
    "Enter a valid session UUID or a credits link containing one.",
  sessionHint: "Find it in the output of your End Credits CLI.",
  sessionSubmit: "Open credits",
  overview: "AT A GLANCE",
  paid: "USDC transferred",
  projects: "Projects credited",
  reserved: "USDC reserved",
  sessions: "Sessions recorded",
  dataNote: "Indexed on-chain activity. Updated every 30 seconds.",
  attention: "Needs your attention",
  held: "{count} pending holds",
  heldBody:
    "Review the screening reason before deciding whether to release a payment.",
  review: "Review holds",
  clearTitle: "Nothing needs a decision.",
  clearBody:
    "Pending holds will appear here. You stay in control of every release.",
  packageTitle: "Your supporting cast",
  packageSubtitle: "Packages that have received or reserved credits.",
  packageEmpty: "The cast is yet to be announced.",
  packageEmptyBody:
    "Once a session pays or reserves a contribution, its packages appear here.",
  browse: "Explore packages",
  activity: "The latest on-chain",
  activitySub: "A receipt for every move.",
  noActivity: "Your first receipt is still ahead.",
  noActivityBody:
    "Escrow activity will appear here after a transaction is indexed.",
  transaction: "View transaction",
  block: "Block {number}",
  events: {
    Held: "Contribution held",
    Released: "Contribution released",
    Denied: "Contribution denied",
    Expired: "Hold expired",
    Reserved: "Contribution reserved",
    Claimed: "Reserve claimed",
    SessionRecorded: "Session recorded",
  },
  escrow: "In the waiting room",
  escrowBody: "Contributions stay accountable, even while they wait.",
  pending: "Awaiting review",
  approved: "Released",
  denied: "Denied",
  expired: "Expired",
  refused: "{count} refused decisions in the log",
  inspect: "Inspect decisions",
  chainDetails: "Data sources & addresses",
  sessionsTitle: "Every session has a story.",
  sessionsBody:
    "Open a session to see the packages, decisions, and receipts behind it.",
  sessionScope:
    "Sessions found in the latest 200 decisions. Uploaded sessions without decisions can be opened by ID.",
  sessionsEmpty: "Ready for your first roll?",
  sessionsEmptyBody:
    "Your agent’s work will leave a trail here once package decisions are recorded. Already have a session link? Open it below.",
  sessionCount: "{count} package decisions",
  sessionCredits: "View credits",
  sessionSearch: "Search by session ID or package",
  sessionNoMatches: "No sessions match your search.",
  sessionLoading: "Finding your sessions…",
  sessionError: "Could not load sessions: {error}",
  loadRetry: "Retry",
  packagesTitle: "Meet the supporting cast.",
  packagesBody:
    "Find an npm package, follow its contributions, or claim the credits waiting for your project.",
  packageCollection: "A few familiar faces",
  explorePackage: "Explore package",
  maintainerTag: "FOR MAINTAINERS",
  maintainerTitle: "Your work.\nYour credits.",
  maintainerBody:
    "Look up your package to check reserved funds. Verify your GitHub ownership and connect a payout wallet when you’re ready.",
  decisionsTitle: "Know where every credit goes.",
  decisionsBody:
    "Filter decisions, read the screening evidence, and follow the receipts.",
  decisionEmptyTitle: "A clean slate.",
  decisionEmptyBody:
    "Your agent’s first credits will appear here, with a reason for every decision.",
  resetFilters: "Clear filters",
  settingsTitle: "Make it your own.",
  settingsBody: "Your budget, your agent, your approval rules.",
  settingsNav: [
    ["budget", "Budget & wallet"],
    ["keys", "Agent connection"],
    ["approvals", "Approvals"],
  ],
  signInTitle: "Your workspace,\nwith you in control.",
  signInBody:
    "Sign in to set a budget, connect your coding agent, and manage contributions waiting for approval.",
  keyIntro:
    "A key connects your local agent to this workspace. Create one for each machine, then install the CLI hook.",
  approvalsIntro:
    "Connect the wallet that approves held contributions. Check pending holds and notifications here.",
  allocation: "Allocation",
  details: "Show evidence",
  recentDecision: "Latest decision",
} as const;
