export const TECHNICAL = {
  eyebrow: "UNDER THE HOOD",
  title: ["A thank-you,", "with an execution trace."],
  body: "From a local tool call to a verifiable receipt. Follow the signals, decisions, and checks that make a contribution possible.",
  example: "ILLUSTRATIVE TRACE · NO LIVE PAYMENTS",
  run: "Run example trace",
  pause: "Pause trace",
  replay: "Replay trace",
  next: "Next stage",
  nav: "Technical pipeline stages",
  local: "YOUR MACHINE",
  server: "END CREDITS",
  chain: "BASE SEPOLIA",
  privacy: "Source code and repo paths stay local.",
  gate: "A stored decision is required before any signature.",
  footer: "Click a stage to inspect it, or run the trace from start to finish.",
  source: "Read the implementation ↗",
  sourceUrl: "https://github.com/zexoverz/end-credits/tree/main/lib",
  stages: [
    {
      title: "Capture",
      icon: "capture",
      label: "01 / LOCAL HOOK",
      heading: "Observe the work. Keep the code local.",
      body: "Claude Code hooks record package reads, imports, dependency additions, and documentation lookups. The recorder stays silent and always exits successfully, so it never interrupts a coding session.",
      detail:
        "Local paths are hashed for evidence. Session uploads contain package attribution signals, not source code or repository paths.",
      codeTitle: "LOCAL SIGNALS → SESSION UPLOAD",
      code: [
        "{",
        '  package: "zod",',
        '  signal: "import",',
        "  count: 3,",
        '  evidence: ["<local-path hash>"]',
        "}",
      ],
      tag: "LOCAL-FIRST ATTRIBUTION",
      checkpoint: "endcredits record → exit 0",
    },
    {
      title: "Attribute",
      icon: "score",
      label: "02 / WEIGHTED ALLOCATION",
      heading: "Credit contribution, with limits.",
      body: "Signals have different weights: adding a dependency scores 5, an import 3, a docs lookup 2, and a package read 1. Repeated signals are capped before the session budget is split.",
      detail:
        "An import is counted across at most 5 files, docs across 5 URLs, and reads across 10 paths. A package’s share cannot exceed your per-package cap.",
      codeTitle: "SCORE → SHARE → CAP",
      code: [
        "dep_added  × 5    once",
        "import     × 3    max 5 files",
        "docs       × 2    max 5 URLs",
        "read       × 1    max 10 paths",
        "",
        "allocation = min(weighted share, cap)",
      ],
      tag: "BUDGET-BOUND CONTRIBUTIONS",
      checkpoint: "Unused budget stays with the owner",
    },
    {
      title: "Screen",
      icon: "shield",
      label: "03 / PAYEE & RISK DECISION",
      heading: "Resolve the payee. Store the decision.",
      body: "Resolve a payout wallet through verified claims, Drips, tea, or npm funding metadata. Intercepta screening feeds a decision alongside funding-change, lookalike, and spam checks.",
      detail:
        "A timeout or screening error means hold, never pay. The outcome and its reasons are persisted before any payment authorization or escrow transaction is built.",
      codeTitle: "PAYEE → SCREEN → PERSIST",
      code: [
        "resolve: claim → Drips → tea → npm",
        "screen:  address + token + impersonation",
        "fallback: simulation when applicable",
        "",
        "timeout / error → HOLD",
        "decision + reasons → database",
      ],
      tag: "FAIL CLOSED",
      checkpoint: "No stored decision → no signature",
    },
    {
      title: "Settle",
      icon: "sign",
      label: "04 / GUARDED EXECUTION",
      heading: "A 402 is a challenge. Not permission.",
      body: "Before signing an x402 payment, End Credits checks the challenge against the screened payee and the credit’s allocation. An address, asset, network, or amount mismatch blocks authorization.",
      detail:
        "Cleared credits use x402. Held and reserved credits take the escrow path. Held releases need the approver wallet’s signature, with World ID step-up where required.",
      codeTitle: "PRE-SIGN CHECKS",
      code: [
        "payTo   === screened payee",
        "asset   === pinned USDC",
        "network === eip155:84532",
        "amount  <=  credit allocation",
        "",
        "stored decision → authorize → settle",
      ],
      tag: "SCREEN FIRST. SIGN SECOND.",
      checkpoint: "Mismatch → no authorization",
    },
    {
      title: "Verify",
      icon: "receipt",
      label: "05 / RECEIPTS & RECOVERY",
      heading: "A decision isn’t a receipt.",
      body: "A completed transfer records a transaction hash. The credits roll keeps the reasons, allocation, and receipt together. MultiBaas indexes escrow and USDC events for the dashboard.",
      detail:
        "Funds reserved for a package without a wallet remain claimable through maintainer verification. Escrowed holds can be released with approval or refunded after denial or expiry.",
      codeTitle: "DECISION + EXECUTION EVIDENCE",
      code: [
        "credit.outcome    → recorded decision",
        "credit.reasons    → why it happened",
        "credit.txHash     → execution receipt",
        "session.recordTx → on-chain session record",
        "",
        "No tx hash ≠ confirmed payment",
      ],
      tag: "AUDITABLE BY DESIGN",
      checkpoint: "Inspect the receipt on Basescan",
    },
  ],
} as const;
