// T8.4: marketing and navigation copy, separate from API messages.
export const WEBSITE = {
  name: "End Credits",
  description: "Give credit to the open-source packages behind your AI coding session. Set a budget, screen every payee, and follow every payment.",
  skip: "Skip to content", navigation: "Main navigation", menu: "Toggle navigation",
  app: "Open app", github: "GitHub", source: "Explore the source", how: "How it works", why: "Why it matters", faq: "Good questions", start: "Get started",
  eyebrow: "A little credit goes a long way.", hero: ["Good code.", "Great credits."],
  intro: "Your agent builds on open source. Give something back to the people behind it, every time a session ends.",
  heroAction: "Give credit where it’s due", heroNote: "Built for Claude Code. Powered by open source.",
  artTitle: ["The people", "behind the", "packages."], artLabel: "OPEN SOURCE, IN THE SPOTLIGHT",
  mintTitle: ["You build.", "We roll", "the credits."], mintNote: "One session. A shared thank-you.",
  setupShort: "A small setup.", setupSub: "A habit of giving back.",
  example: "ILLUSTRATIVE SESSION", rollTitle: "And the credits go to…", rollSub: "A place for every contribution.",
  rollPackages: ["zod", "date-fns", "chalk"], exampleStatus: "Recognized",
  sessionDone: "Session complete", sessionSub: "Time to give credit.", network: "USDC on Base Sepolia",
  strip: "Small contributions. Real infrastructure.", partners: ["Intercepta", "Curvegrid", "World", "x402"], partnerRoles: ["Payee screening", "On-chain visibility", "Human verification", "Payments"],
  flowEyebrow: "FROM YOUR FIRST PROMPT TO THE FINAL CREDIT", flowTitle: ["Keep making things.", "We’ll handle the thank-you."],
  flowBody: "No new ritual after every session. Set your limits, connect the hook, and let your work leave a little something behind.",
  steps: [
    { title: "Make it yours.", body: "Choose a session budget and a per-package limit. Connect an agent key and install the Claude Code hook.", label: "01 / SET UP", tab: "Set up", terminal: ["$ endcredits init", "✓ Claude Code hooks installed", "$ endcredits key <your-agent-key>", "✓ Ready for your next session"] },
    { title: "Build something good.", body: "The hook records package reads, imports, and installs. Your code and repository paths stay on your machine.", label: "02 / BUILD", tab: "Build", terminal: ["$ claude", "> Build a report with date formatting", "→ package signals recorded locally", "→ zod · date-fns · chalk"] },
    { title: "Leave a little credit.", body: "Your budget is split by usage. Payees are screened before signing, and each decision has a reason you can inspect.", label: "03 / GIVE BACK", tab: "Give back", terminal: ["$ endcredits settle", "→ attribute package contributions", "→ screen payees before signing", "→ open your session’s credits"] },
  ],
  workflowLabel: "How End Credits works", workflowExample: "WORKFLOW PREVIEW · EXAMPLE OUTPUT", automation: "Less admin. More making.",
  privacy: "Your code stays yours.", privacyBody: "Package signals leave the session. Your source code and repo paths don’t.",
  budgetLabel: "YOU SET THE LIMITS", budgetTitle: "Small budget.\nShared impact.", budgetSlider: "Illustrative session budget in USDC", budgetExample: "Interactive example, not a saved setting.", budgetUnit: "USDC / session", budgetAction: "Set your actual budget",
  connectionTitle: "Made for the way\nyou already build.", connectionSub: "One hook. Your usual workflow.", integrationChips: ["Claude Code", "npm packages", "GitHub", "USDC", "Base"],
  safeEyebrow: "GENEROUS, WITH GUARDRAILS", safeTitle: ["Good intentions.", "Careful payments."],
  safeBody: "Paying a package means finding its maintainer, checking its payee, and knowing when to wait. Every credit comes with a decision.",
  outcomes: [
    { id: "paid", label: "Paid", symbol: "↗", heading: "To the people behind it.", body: "A cleared payee can receive USDC over x402. The credits page shows a transaction link when the payment succeeds.", note: "SCREEN FIRST. SIGN SECOND." },
    { id: "capped", label: "Capped", symbol: "↔", heading: "Generosity has a limit.", body: "A package’s allocation stops at your per-package cap. You stay in control of how much any one project can receive.", note: "YOUR LIMITS, RESPECTED." },
    { id: "held", label: "Held", symbol: "Ⅱ", heading: "Some things deserve a pause.", body: "A concern or screening error means hold, never pay. Escrowed funds wait for approval and return on denial or expiry.", note: "UNCERTAINTY ISN’T PERMISSION." },
    { id: "reserved", label: "Reserved", symbol: "◷", heading: "No wallet? Still in the credits.", body: "Funds can be reserved for packages without a payout wallet. Maintainers verify ownership through GitHub and claim their share.", note: "A CONTRIBUTION WORTH KEEPING." },
    { id: "refused", label: "Refused", symbol: "×", heading: "A clear reason to say no.", body: "High-risk payees, lookalike addresses, and spam patterns are refused. Nothing is sent, and the reason is recorded.", note: "EVERY DECISION HAS A REASON." },
  ],
  outcomeTabs: "Explore payment outcomes", history: "See the decision history",
  measurementEyebrow: "THE GAP WE’RE HERE TO CLOSE", measurementTitle: ["Open source gives a lot.", "Getting paid is harder."],
  measurementBody: "We checked the top 1,000 npm packages. Many ask for support. Very few list a wallet an agent can pay.",
  measurementLabel: "list a payable wallet", measurementOther: "have any funding metadata", measurementNumber: "2.1%", measurementOtherNumber: "41.6%",
  measurementFootnote: "Top 1,000 npm packages · 25 Sep 2026 · 21 packages, 10 repositories with wallets.",
  measurementGrid: "21 highlighted dots out of 1,000 represent packages with a payable wallet.", reserveLink: "That’s why we reserve funds",
  faqTitle: ["A few things", "you might be wondering."],
  faqs: [
    { q: "Is this a fee for using open source?", a: "No. End Credits is voluntary support, never a paywall. Package licenses and access stay exactly as they are. You choose whether to contribute and set the budget." },
    { q: "What leaves my machine?", a: "Package attribution signals, not your source code or repository paths. The local hook records package reads, imports, and installs, then the session’s package credits are uploaded." },
    { q: "What if a package doesn’t have a wallet?", a: "Its share can be reserved in EndCreditsEscrow. The maintainer signs in with GitHub, proves repository ownership, and adds a payout wallet through a funding pull request." },
    { q: "What happens if screening fails?", a: "A timeout or error from Intercepta means hold, never pay. No payment authorization is signed without the required stored decision and payment checks." },
    { q: "Is this on mainnet?", a: "This version runs on Base Sepolia using testnet USDC. It is a working testnet project built for ETHGlobal Tokyo 2026." },
  ],
  setupEyebrow: "YOUR NEXT SESSION COULD GIVE SOMETHING BACK", setupTitle: ["Good work deserves", "end credits."],
  setupBody: "Clone the project, build the CLI, and connect your agent. Then get back to doing your thing.", setupTerminal: "Terminal / from a local clone",
  setupCommands: ["pnpm install", "pnpm --filter endcredits build", "cd cli && npm link && cd ..", "endcredits init", "endcredits key <token> --api https://end-credits.up.railway.app"],
  clone: "Clone the repository first", ownerKey: "Create your agent key", copy: "Copy commands", copied: "Copied!", copyError: "Couldn’t copy. Select the commands to copy them manually.",
  setupHint: "Replace <token> with your agent key. Run init inside the project you want to support.",
  footer: "For the people behind the packages.", footerNote: "Built at ETHGlobal Tokyo 2026. Open source, of course.", contract: "Escrow contract", top: "Back to top",
  productNav: [["/app", "Dashboard"], ["/history", "History"], ["/owner", "Owner"]],
} as const;
