export const WORKSPACE = {
  ownerTitle: "Your control desk.",
  ownerBody: "A small set of rules. A clear record of what happens next.",
  activityTitle: "The work. And its credits.",
  activityBody:
    "Your agent’s sessions, open-source cast and contribution receipts.",
  setup: "First, make it yours.",
  ready: "Ready for your next session.",
  readyBody: "Your seven setup checks are complete.",
  setupDetail: "Review setup",
  setupClose: "Hide setup",
  refresh: "Refresh",
  close: "Close panel",
  complete: "complete",
  budget: "Contribution rules",
  budgetBody: "Choose what each session can give.",
  editBudget: "Edit rules",
  session: "Per session",
  package: "Per package",
  daily: "Daily limit",
  walletDetails: "Wallet addresses",
  allowance: "Spending permission",
  allowanceBody: "USDC stays in your wallet until a session spends it.",
  editAllowance: "Manage allowance",
  left: "Available this period",
  unavailable: "Not available",
  notSet: "Not set yet",
  configured: "Configured",
  review: "Review",
  unit: "USDC",
  approver: "Your signature",
  approverBody: "The wallet that releases held contributions.",
  editApprover: "Manage approver",
  agent: "Agent connection",
  agentBody: "A key for your machine. Hooks for your project.",
  editAgent: "Manage keys",
  connected: "Agent key ready",
  connect: "Connect your agent",
  identity: "Sign-in wallet",
  notifications: "Notifications",
  held: "Held contributions",
  heldBody: "Read the evidence before you sign.",
  noHolds: "No contributions need your signature.",
  openHolds: "Review holds",
  allHolds: "See every hold",
  firstSession: "Open latest session",
  inbox: "Next moves",
  inboxBody: "A signature from you. A claim from a maintainer.",
  sign: "To sign",
  claim: "To claim",
  all: "All",
  evidence: "Why this is here",
  expiring: "Expires soon",
  expires: "Expires",
  noActions: "Nothing waiting here.",
  noActionsBody: "New holds and reserves appear here as they are recorded.",
  unknownPackage: "Unidentified package",
  unknownTip: "Held contribution",
  source: "Source",
  previous: "Previous page",
  next: "Next page",
  page: "Page",
  of: "of",
  sessionColumn: "Session / supporting packages",
  decisionColumn: "Decisions",
  sessions: "Sessions",
  entries: "records",
  details: "Details",
  credits: "Open credits",
  morePackages: "more packages",
  ledger: "Escrow, at a glance.",
  ledgerBody: "Recorded hold outcomes",
  pending: "Awaiting review",
  released: "Released",
  denied: "Denied",
  expired: "Expired",
  decisions: "Open decisions",
  history: "Recorded activity",
  noLedger: "No hold events recorded yet.",
  activity: "Open activity",
  openSession: "Open a session",
  controls: "Controls",
  live: "On-chain activity",
  setupGuide: "Setup guide",
} as const;
