// Regenerates lib/chain/abi.ts from the Foundry artifact.
// Run after `cd contracts && forge build`: `pnpm tsx scripts/gen-abi.ts`.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(__dirname, "..");
const artifactOf = (name: string) => path.join(root, `contracts/out/${name}.sol/${name}.json`);
const target = path.join(root, "lib/chain/abi.ts");

const erc20Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "transfer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "event",
    name: "Transfer",
    anonymous: false,
    inputs: [
      { name: "from", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "value", type: "uint256", indexed: false },
    ],
  },
];

const readAbi = (name: string) =>
  (JSON.parse(readFileSync(artifactOf(name), "utf8")) as { abi: unknown[] }).abi;
const abi = readAbi("EndCreditsEscrow");
const budgetAbi = readAbi("EndCreditsBudget");

const out = `// Generated by scripts/gen-abi.ts from contracts/out. Do not edit by hand.

export const escrowAbi = ${JSON.stringify(abi, null, 2)} as const;

export const budgetAbi = ${JSON.stringify(budgetAbi, null, 2)} as const;

export const erc20Abi = ${JSON.stringify(erc20Abi, null, 2)} as const;
`;

writeFileSync(target, out);
console.log(`wrote ${path.relative(root, target)} (${abi.length} escrow, ${budgetAbi.length} budget entries)`);
