// T4.1: probe Intercepta with the SPEC §7.4 demo addresses, three real maintainer payees and Base
// USDC, then write the raw responses to docs/intercepta-probe.md. Exactly 10 requests.
//
//   INTERCEPTA_API_KEY="$(cat ~/.config/dominion/intercepta-key)" \
//   INTERCEPTA_BASE=https://api.web3antivirus.io pnpm tsx scripts/probe-intercepta.ts
//
// The key is read from env and never printed. Real maintainer results are recorded for our own
// demo prep only; nothing here labels a real package (AGENTS rule 9).
import { writeFileSync } from "node:fs";
import type { NewScreen, ScreenRepo } from "../lib/intercepta/cache";
import { createIntercepta } from "../lib/intercepta/client";
import { BASE_MAINNET, BASE_USDC } from "../lib/intercepta/mapping";
import { readEnv } from "../lib/env";

const DEMO = [
  { address: "0x098B716B8Aaf21512996dC57EB0615e2383E2f96", label: "OFAC SDN, Lazarus Group (Ronin)" },
  { address: "0x7F367cC41522cE07553e823bf3be79A889DEbe1B", label: "OFAC SDN" },
  { address: "0x3da02e1f29bcbed185eca0d3299efd46e6e7e155", label: "phishing receiver (ScamSniffer)" },
] as const;

const MAINTAINERS = [
  { address: "0xF233A42130Bcdd8b22FFB5D9593199f31C3Eeb87", label: "zod (tea.yaml)" },
  { address: "0x3A39F5E9BFe0a90e394982492e166C5635893141", label: "prettier (FUNDING.json drips)" },
  { address: "0xD5371B61b35E13F2ae354BE95081aD63FB383452", label: "TanStack/query (FUNDING.json drips)" },
] as const;

// Captures every row the client would store, so the doc shows exactly what went into `screens`.
function captureRepo() {
  const rows: (NewScreen & { id: string })[] = [];
  const repo: ScreenRepo = {
    latestOk: async () => null, // never cache: each call below is a real request
    insert: async (row) => {
      const id = `probe-${rows.length + 1}`;
      rows.push({ ...row, id });
      return id;
    },
  };
  return { repo, rows };
}

async function main() {
  const { repo, rows } = captureRepo();
  const c = createIntercepta({ base: readEnv("INTERCEPTA_BASE"), apiKey: readEnv("INTERCEPTA_API_KEY"), repo });
  const labels: string[] = [];

  for (const d of [...DEMO, ...MAINTAINERS]) {
    labels.push(`quick-scan ${d.label}`);
    await c.quickScan(d.address);
  }
  for (const d of DEMO) {
    labels.push(`impersonation ${d.label}`);
    await c.checkImpersonation(d.address);
  }
  labels.push("token risks Base USDC");
  await c.tokenRisks(BASE_USDC, BASE_MAINNET);

  const sections = rows.map((r, n) =>
    [
      `### ${n + 1}. ${labels[n]}`,
      "",
      `\`${r.kind}\` \`${r.subject}\`${r.chainId ? ` chain ${r.chainId}` : ""}, HTTP ${r.status}, ${r.latencyMs} ms`,
      "",
      "```json",
      JSON.stringify(r.response, null, 2),
      "```",
    ].join("\n"),
  );
  const doc = [
    "# Intercepta probe (T4.1)",
    "",
    `Run ${new Date().toISOString()} against ${readEnv("INTERCEPTA_BASE")}, ${rows.length} requests.`,
    "Generated by `scripts/probe-intercepta.ts`; responses are verbatim.",
    "",
    ...sections,
    "",
  ].join("\n");
  writeFileSync("docs/intercepta-probe.md", doc);
  process.stdout.write(`wrote docs/intercepta-probe.md (${rows.length} requests)\n`);
}

main().catch((e: unknown) => {
  process.stderr.write(`probe failed: ${e instanceof Error ? e.message : String(e)}\n`);
  process.exit(1);
});
